# Generated by Django 3.2.8 on 2021-11-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='_perfis_perfil_contatos_+', to='perfis.Perfil'),
        ),
    ]
